Customer:
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (771394034, 'William', 'Joseph', '1976-08-20', '626 Michael Street', 'Spain', 'Seville', 'william.joseph@example.com', 'william123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (858995015, 'Donna', 'Linda', '1977-03-12', '103 Anthony Street', 'Italy', 'Milan', 'donna.linda@example.com', 'donna123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (666969748, 'William', 'Donald', '1966-02-25', '808 Anthony Street', 'Spain', 'Seville', 'william.donald@example.com', 'william123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (488478542, 'Christopher', 'Christopher', '1988-12-01', '478 Robert Street', 'USA', 'Philadelphia', 'christopher.christopher@example.com', 'christopher123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (659818948, 'Richard', 'Donald', '1975-12-13', '207 Daniel Street', 'Egypt', 'Port Said', 'richard.donald@example.com', 'richard123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (101486315, 'Elizabeth', 'Ashley', '1944-08-05', '403 Charles Street', 'Italy', 'Palermo', 'elizabeth.ashley@example.com', 'elizabeth123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (580940126, 'Betty', 'Susan', '1978-01-24', '348 Kenneth Street', 'Australia', 'Adelaide', 'betty.susan@example.com', 'betty123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (524765073, 'Nancy', 'Barbara', '1978-06-01', '208 Donald Street', 'USA', 'San Diego', 'nancy.barbara@example.com', 'nancy123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (331782474, 'Ashley', 'Emily', '1990-02-28', '644 Robert Street', 'USA', 'Los Angeles', 'ashley.emily@example.com', 'ashley123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (611006387, 'Matthew', 'Joseph', '1953-05-10', '611 Michael Street', 'UK', 'Birmingham', 'matthew.joseph@example.com', 'matthew123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (726956725, 'Donald', 'Joseph', '1969-02-17', '55 Mark Street', 'Italy', 'Bari', 'donald.joseph@example.com', 'donald123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (483137456, 'Jessica', 'Barbara', '1950-02-01', '378 Joseph Street', 'China', 'Shenzhen', 'jessica.barbara@example.com', 'jessica123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (387368824, 'Mary', 'Nancy', '2001-08-09', '997 Steven Street', 'Spain', 'Valencia', 'mary.nancy@example.com', 'mary123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (831697258, 'Karen', 'Susan', '1973-09-26', '975 Mark Street', 'Canada', 'Quebec City', 'karen.susan@example.com', 'karen123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (389624700, 'Richard', 'Joseph', '1989-01-22', '651 Daniel Street', 'China', 'Chengdu', 'richard.joseph@example.com', 'richard123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (570813685, 'Donald', 'William', '1993-02-25', '926 Joseph Street', 'Canada', 'Calgary', 'donald.william@example.com', 'donald123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (524399450, 'Sarah', 'Margaret', '1958-02-05', '333 Joseph Street', 'Spain', 'Las Palmas', 'sarah.margaret@example.com', 'sarah123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (768974760, 'Donald', 'Daniel', '1966-01-06', '113 Paul Street', 'Germany', 'Berlin', 'donald.daniel@example.com', 'donald123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (214871907, 'Robert', 'Donald', '1993-05-21', '464 Thomas Street', 'Italy', 'Venice', 'robert.donald@example.com', 'robert123');
INSERT INTO Customer (ssn, Fname, Lname, Bdate, Street, CountryName, City, Email, Password) VALUES (881922253, 'Betty', 'Barbara', '1966-08-12', '76 Christopher Street', 'Canada', 'Montreal', 'betty.barbara@example.com', 'betty123');
Offices:
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (664805983, 'Oak Street', 'Canada', 'Halifax');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (104471362, 'Oak Street', 'Japan', 'Fukuoka');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (536095548, 'Maple Street', 'Germany', 'Frankfurt');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (515892535, 'Maple Street', 'China', 'Beijing');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (242756734, 'Cedar Street', 'Spain', 'Bilbao');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (881728329, 'Elm Street', 'China', 'Hangzhou');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (871976323, 'Cedar Street', 'France', 'Montpellier');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (443137386, 'Cedar Street', 'Italy', 'Naples');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (438291899, 'Oak Street', 'Japan', 'Nagoya');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (814702753, 'Cedar Street', 'Egypt', 'Cairo');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (871399701, 'Elm Street', 'USA', 'San Diego');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (802668686, 'Oak Street', 'UK', 'Glasgow');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (413542946, 'Elm Street', 'USA', 'Houston');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (488215919, 'Maple Street', 'France', 'Bordeaux');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (698420278, 'Pine Street', 'USA', 'Phoenix');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (219127463, 'Oak Street', 'Japan', 'Tokyo');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (233305719, 'Oak Street', 'Japan', 'Nagoya');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (897298748, 'Oak Street', 'France', 'Bordeaux');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (491764844, 'Cedar Street', 'Australia', 'Canberra');
INSERT INTO Office (telephone, Street, CountryName, City) VALUES (696244668, 'Pine Street', 'USA', 'Chicago');
Car:
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('TT Convertible', 'Red', 2023, 87238.27, 7, 'Manual', 'Audi', 9394, 192.3, 14);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('SQ7 Premium Plus SUV', 'Red', 2018, 93082.96, 3, 'Automatic', 'Audi', 8754, 130.89, 9);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('i30 Techno Hatchback', 'Black', 2012, 5352.95, 5, 'Automatic', 'Hyundai', 7032, 30.57, 3);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('A1 Sportback Hatchback', 'Blue', 2014, 55291.58, 2, 'Manual', 'Audi', 6730, 69.03, 5);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('Verano Leather Sedan', 'Silver', 2017, 79905.01, 3, 'Automatic', 'Buick', 5410, 125.71, 11);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('Challenger SRT Coupe', 'White', 2004, 18244.11, 4, 'Automatic', 'Dodge', 4945, 114.79, 10);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('Civic LX Coupe', 'Red', 2002, 68200.7, 4, 'Automatic', 'Honda', 4561, 104.49, 17);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('Vanquish 2+2 Coupe', 'Silver', 2001, 95592.17, 3, 'Manual', 'Aston Martin', 4967, 22.47, 3);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('595 Competizione Convertible', 'Red', 2006, 78690.51, 3, 'Automatic', 'Abarth', 7482, 121.49, 8);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('Cruze LTZ Hatchback', 'Red', 2008, 62208.38, 3, 'Automatic', 'Chevrolet', 6562, 21.93, 8);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('A3 Ambition Convertible', 'Silver', 2021, 94938.84, 2, 'Automatic', 'Audi', 3397, 60.45, 1);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('Stelvio SUV', 'Blue', 2002, 70820.16, 5, 'Manual', 'Alfa Romeo', 1806, 77.13, 14);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('X3 M40i SUV', 'Red', 2005, 29663.25, 2, 'Automatic', 'BMW', 1122, 149.92, 8);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('Enclave Avenir SUV', 'Red', 2007, 93162.32, 2, 'Manual', 'Buick', 4856, 156.08, 13);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('Civic Type-R Hatchback', 'Blue', 2009, 86878.5, 2, 'Manual', 'Honda', 8292, 185.64, 8);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('Charger GT Sedan', 'Red', 2022, 27092.27, 4, 'Manual', 'Dodge', 6887, 48.77, 16);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('i30 Fastback Feel Hatchback', 'Black', 2014, 22089.45, 6, 'Automatic', 'Hyundai', 3029, 148.78, 6);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('Cascada Premium Convertible', 'Blue', 2018, 6276.77, 5, 'Manual', 'Buick', 3492, 52.4, 9);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('Audi A4', 'Black', 2021, 60898.93, 2, 'Manual', 'Audi', 2781, 29.27, 20);
INSERT INTO Car (model, color, year, kilometers, seatNums, transmissionType, make, plateID, pricePerDay, officeID) VALUES ('Accord Hybrid Sedan', 'Black', 2011, 55417.45, 4, 'Manual', 'Honda', 1122, 30.6, 10);
Employees:
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (412452582, 'John', 'William', '1990-10-18', 'Maple Street', 'Japan', 'Kawasaki', 'john.william@company.com', 'john123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (558828519, 'Charles', 'Anthony', '1957-04-10', 'Oak Street', 'USA', 'Philadelphia', 'charles.anthony@company.com', 'charles123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (285316442, 'Nancy', 'Margaret', '1998-11-01', 'Elm Street', 'Egypt', 'Mansoura', 'nancy.margaret@company.com', 'nancy123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (132570521, 'Lisa', 'Donna', '1980-08-05', 'Cedar Street', 'China', 'Hangzhou', 'lisa.donna@company.com', 'lisa123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (977287118, 'Linda', 'Mary', '1944-09-13', 'Elm Street', 'Canada', 'Montreal', 'linda.mary@company.com', 'linda123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (144022514, 'Paul', 'Richard', '1988-06-24', 'Maple Street', 'Italy', 'Turin', 'paul.richard@company.com', 'paul123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (348230694, 'Emily', 'Patricia', '1979-08-07', 'Cedar Street', 'Egypt', 'Alexandria', 'emily.patricia@company.com', 'emily123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (164392202, 'Mary', 'Barbara', '1992-05-02', 'Oak Street', 'Australia', 'Wollongong', 'mary.barbara@company.com', 'mary123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (173025681, 'Joseph', 'Charles', '1960-01-07', 'Maple Street', 'Egypt', 'Luxor', 'joseph.charles@company.com', 'joseph123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (136145660, 'Donna', 'Margaret', '1992-12-23', 'Oak Street', 'USA', 'Dallas', 'donna.margaret@company.com', 'donna123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (232850793, 'Patricia', 'Patricia', '1958-05-31', 'Cedar Street', 'Spain', 'Bilbao', 'patricia.patricia@company.com', 'patricia123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (203703880, 'Matthew', 'William', '1950-04-23', 'Pine Street', 'USA', 'Dallas', 'matthew.william@company.com', 'matthew123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (228695518, 'Donna', 'Sarah', '2003-10-15', 'Oak Street', 'UK', 'London', 'donna.sarah@company.com', 'donna123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (696725802, 'Ashley', 'Kimberly', '2000-02-13', 'Cedar Street', 'Canada', 'Vancouver', 'ashley.kimberly@company.com', 'ashley123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (880529148, 'William', 'Joseph', '1996-05-24', 'Elm Street', 'Canada', 'Winnipeg', 'william.joseph@company.com', 'william123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (303397156, 'Karen', 'Jessica', '1995-11-01', 'Oak Street', 'Spain', 'Barcelona', 'karen.jessica@company.com', 'karen123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (181885981, 'Jessica', 'Kimberly', '1948-07-22', 'Maple Street', 'Egypt', 'Mansoura', 'jessica.kimberly@company.com', 'jessica123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (578753258, 'Susan', 'Margaret', '1993-05-09', 'Elm Street', 'Canada', 'Halifax', 'susan.margaret@company.com', 'susan123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (540601810, 'Donald', 'Michael', '1953-03-11', 'Maple Street', 'Australia', 'Adelaide', 'donald.michael@company.com', 'donald123');
INSERT INTO Employee (ssn, Fname, Lname, Bdate, street, CountryName, City, Email, Password) VALUES (334549142, 'Sarah', 'Karen', '1973-12-11', 'Oak Street', 'USA', 'San Jose', 'sarah.karen@company.com', 'sarah123');
